name: Deploy to Glitch

on:
  push:
    branches: [ main ]

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - name: repo-sync
      uses: wei/git-sync@v1
      env:
        SOURCE_REPO: "https://github.com/wellcomecollection/ingest-inspector.git"
        SOURCE_BRANCH: "main"
        DESTINATION_REPO: ${{ secrets.glitch_git_URL }}
        DESTINATION_BRANCH: "main"
      with:
        args: "$SOURCE_REPO" "$SOURCE_BRANCH" "$DESTINATION_REPO" "$DESTINATION_BRANCH"
